### PR TITLE
PLATO-552: Image Viewer Quiz Mode : Build accessible toggle

### PR DESCRIPTION
**Pull request by jialin-he**
Resolves PLATO-552
Resolves PLATO-205

## Description

- Create a toggle-button component
- Insert it in the image viewer

## Checks

**Have you written any necessary unit tests?**

- [ ] Yes
- [ ] Not yet
- [x] Not applicable

**Have you added or updated any necessary integration tests?**

- [ ] Yes
- [x] Not yet
- [ ] Not applicable

**Browsers tested on:**

- [x] Chrome
  - [ ] Mobile
- [ ] Safari
  - [ ] Mobile
- [ ] Firefox
  - [ ] Mobile
- [ ] Edge
- [ ] IE11
- [ ] Not applicable

### CODE REVIEW

**Comment by michael-iden** [comment]
I am seeing the toggles get a little out of sync when testing on latest Chrome

image

When the "SHOW" toggle is disabled, clicking on the circle region doesn't have any effect, but clicking on the label performs the correct toggle. When show is enabled it, it can be disabled by clicking on the circular slider region. 

Also I can see the quiz mode toggle can get out of sync with actually showing the metadata for an image

**Comment by jialin-he** [comment]
@michael-iden Problems solved now!

**Comment by michael-iden** [comment]
Hey I noticed the captions may be a little bit off based off the mockup attached to https://jira.jstor.org/browse/PLATO-205

Personally, I would actually have the caption be static instead of flipping between "SHOW/HIDE". I think of this toggle like a fancy checkbox and rarely do the labels for checkboxes change. To me, it would make the most sense to do "Show Caption" as the label all the time for the bottom left toggle and if it's off we don't show the caption. This is probably a question for @sandsng though. 

Current state seems kinda contradictory:
image

**Comment by michael-iden** [comment]
I also noticed that the hide/show toggle interacts a little differently with the quiz mode toggle depending on if you started in presentation mode vs study mode. The interaction is a bit difficult to explain but maybe we can take a look at it on a call and determine if this is something worth solving.

**Comment by jialin-he** [comment]
@michael-iden I just updated the captions to be like the mockup. We can talk tomorrow about other  possible changes!

**Comment by sandsng** [comment]
@jialin-he @michael-iden Going with Mike's suggestion of making the label static "SHOW CAPTION" all of the time seems like an improvement. We just need to make sure that the state of the caption is read aloud via screen reader, possibly using `aria-switch` or something similar.

**Comment by jialin-he** [comment]
@sandsng How about the quiz mode and shuffle? Do we also want them to be some static words all the time?

**Comment by jialin-he** [comment]
Talked to Nick via Slack, we are going to keep other two toggles as is. Caption toggle has been updated.

**Review by michael-iden — APPROVED** [review]

**Review by willschoener — APPROVED** [review]

**Pull request merged**
